### ISSUE TITLE
Mask size not equal picture size 

### ISSUE THREAD

**Issue by lingxian55** [Sanster/lama-cleaner#185] opened 2023-01-15 13:52 UTC
![image](https://user-images.githubusercontent.com/33617805/212544712-0a856879-a389-4a8e-aac1-60a431c4d7bc.png)
my command : lama-cleaner --model=cv2 --device=cpu --local-files-only --port=8080 --debug
how to fix this error

**Comment by Sanster** [comment] 2023-01-15 14:28
It may be a bug caused by image EXIF, we need to find an image to reproduce it

**Comment by Sanster** [comment] 2023-01-17 13:39
fixed in `0.32.1`

**Closed** 2023-01-17 22:34 UTC
Labels: bug
